name: Android Release

# 1
on:
  create:
    tags:
      - v*
  # 2
  push:
    branches: [ "master","main" ]
  pull_request:
    branches: [ "master","main" ]

  # 3
  workflow_dispatch:

# 4
jobs:
  # 5
  build:
    # 6
    runs-on: ubuntu-latest

    # 7
    steps:
      # 8
      - uses: actions/checkout@v3
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      # 10   
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter pub get    
    
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      # 12
  

      # Runs a set of commands using the runners shell
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.TOKEN }}